## Initalization

In [ ]:

words_set = set()
# for line in lines()

In [ ]:
from Embed_Align_Net import *

In [ ]:
with open('../models/embed_align-5001.model', 'rb') as f:
    model = pickle.load(f)

In [ ]:
torch.save(model.state_dict(), '../models/embed_align-5001.torch-model')

In [ ]:
with open('../data/processed/english-french_large/training-30000.en', 'r') as f:
    full_text = f.read().splitlines()
    
for line in full_text:
    words = line.split()
    for word in words:
        words_set.add(word)

In [73]:
x = torch.tensor([1 ,0, 1.0])
x = x.repeat(2, 1)

y = torch.tensor([[1, -2, 3.0], [4, 4, 4.0]])

z = torch.cat([x, y], dim=1)

In [88]:
a = [0] * 4
torch.LongTensor(a)

tensor([ 0,  0,  0,  0])

In [74]:
import torch.nn.functional as F

zz = F.relu(z).sum(dim = 0)
zz1 = F.softplus(zz)

In [76]:
# print(x)
print(z)
print(F.relu(z))
print(zz)
print(zz1)

tensor([[ 1.,  0.,  1.,  1., -2.,  3.],
        [ 1.,  0.,  1.,  4.,  4.,  4.]])
tensor([[ 1.,  0.,  1.,  1.,  0.,  3.],
        [ 1.,  0.,  1.,  4.,  4.,  4.]])
tensor([ 2.,  0.,  2.,  5.,  4.,  7.])
tensor([ 2.1269,  0.6931,  2.1269,  5.0067,  4.0181,  7.0009])


In [77]:
import torch
import torch.distributions as distributions
import torch.optim as optim

In [2]:
from BSG_Net import *
import pickle
from utils import *


In [4]:
with open('../models/bsg-300.model', 'rb') as f:
    model = pickle.load(f)
    
create_vocabulary('../data/processed/english-french_large/training-300.en')

In [5]:
def divergence_closed_form(mu_1, sigma_1, mu_2, sigma_2):
    posterior = distributions.MultivariateNormal(mu_1, torch.diag(sigma_1 ** 2))
    prior = distributions.MultivariateNormal(mu_2, torch.diag(sigma_2 **2))
    kl_z = torch.distributions.kl.kl_divergence(posterior, prior)

    return kl_z

cos = nn.CosineSimilarity(dim=0, eps=1e-6)

## Entailment recognition

In [38]:
one = one_hot('senate')
two = one_hot('senator')

mean_one = model.p_mean(one)
sigma_one = model.p_sigma(one)

mean_two = model.p_mean(two)
sigma_two = model.p_sigma(two)

print('KL')
print(divergence_closed_form(mean_one, sigma_one, mean_two, sigma_two).item())

# print('cosine similarity')
# sim = torch.dot(mean_one, mean_two) / (torch.norm(mean_one) * torch.norm(mean_two))
# print(sim)

KL
5.876708984375


In [ ]:
# positive 

one = one_hot('committee')
two = one_hot('commission')

In [ ]:
# negative examples

one = one_hot('senate')
two = one_hot('senator')

one = one_hot('speaker')
two = one_hot('1950')


In [ ]:
import torch.nn as nn
import torch.nn.functional as F

a = torch.tensor([1.0, 2.0])

print(F.softmax(a, dim=0))

## Lexical Substitution Task

In [ ]:
a = 'side.n	301	29	on sunday at craven cottage , jose mourinho and his all stars exhibited all of the above symptoms and they were made to pay the price by a fulham side that had in previous weeks woken up after matches with their heads kicked in .'



In [ ]:
def get_context_words(center_position, sentence, context_size):
    '''
    Return a list of context words for the given center word

    @param center_position position of center word in the sentence
    @param sentence
    @param context_size
    @return context_words: list of words
    '''

    words = sentence.split()

    context_words = []
    for j in range(max(0, center_position - context_size), min(len(words), center_position + context_size + 1)):
        if j == center_position:  # center_word is included in this range, ignore that
            continue
        context_words.append(words[j])

    return context_words

In [ ]:
pos = 2
sent = 'on our side : provide more aid , untied to trade ; write off debt ; help with good governance and infrastructure ; training to the soldiers , with un blessing , in conflict resolution ; encouraging investment ; and access to our markets so that we practise the free trade we are so fond of preaching .'

get_context_words(pos, sent, 3)

In [ ]:
with open('../data/processed/english-french_large/training-300.en', 'r') as f:
    data = f.read().splitlines()

In [ ]:
data[0]

In [ ]:
from utils import *

create_vocabulary('../data/processed/english-french_large/training-300.en')

In [ ]:
global_w2i.keys()

In [ ]:
'.' in global_w2i.keys()

In [ ]:
a = {'1': '2'}

for k, v in a.items():
    print(k)
    print(v)